#
# Startit (v1.2.1): .travis.yml
# Copyright (c) 2019 Adorade. All Rights Reserved.
# Licensed under MIT
#
# Travis continuous integration system configuration file.
# Overview on how to customize the configuration is located at:
# http://docs.travis-ci.com/user/customizing-the-build/

language: node_js

node_js:
  - "lts/*"

dist: focal

git:
  depth: 4

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn global add gulp-cli

script:
  - yarn run verify
  - yarn run test
  - yarn run build
