#
# Startit (v1.2.0): .travis.yml
# Copyright (c) 2019 Adorade. All Rights Reserved.
# Licensed under MIT
#
# Travis continuous integration system configuration file.
# Overview on how to customize the configuration is located at:
# http://docs.travis-ci.com/user/customizing-the-build/

language: node_js

# Blocklist branches that you don't want to be built
branches:
  except:
    - experimental
    # prevent tagged commits from being built
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# Build matrix
matrix:
  fast_finish: true
  include:
    - name: "Linux Node lts/*"
      node_js: "lts/*"
      os: linux
      dist: xenial
    - name: "Linux Node 12"
      node_js: "12"
      os: linux
      dist: xenial
    - name: "macOs Node lts/*"
      node_js: "lts/*"
      os: osx
    - name: "macOs Node 12"
      node_js: "12"
      os: osx
    - name: "Windows Node lts/*"
      node_js: "lts/*"
      os: windows
      env: YARN_GPG=no # starts gpg-agent that never exits
    - name: "Windows Node 12"
      node_js: "12"
      os: windows
      env: YARN_GPG=no # starts gpg-agent that never exits

# Travis uses yarn@1.3.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn --frozen-lockfile --non-interactive --network-timeout 300000

cache:
  yarn: true

before_script:
  - yarn global add gulp-cli
  - node -v && npm -v && yarn -v && git --version && gulp -v

script:
  - yarn run test
  - yarn run build
