sudo: required
language: node_js
node_js:
  - "lts/*"

before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.12.3-1

cache:
  yarn: true

before_script:
  - yarn global add gulp-cli
script: gulp build --production
