# GitHub Actions allows you to build, test, and deploy applications in your language of choice
name: Node CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  schedule:
  - cron: 0 3 * * 1-5

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: [10.x, 12.x]
        exclude:
        - os: windows-latest
          node_version: 10.x
        - os: macOS-latest
          node_version: 10.x

    runs-on: ${{ matrix.os }}

    steps:
    # checkout the repo
    - name: Checkout the repo
      uses: actions/checkout@v1

    # use node.js matrix
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    # install dependencies, test and build
    - name: Clean install dependencies and build
      run: |
        yarn install
        yarn run test
        yarn run build
      shell: bash
      env:
        CI: true

    # deploy web app using publish profile credentials
    # coming soon
